[package]
name = "hike_audio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fyrox-sound = "0.33"
rand = { workspace = true }
rogalik = { workspace = true }

hike_game = { path = "../hike_game" }
