[package]
name = "tower"
version = "0.1.0"
edition = "2021"

[package.metadata.android]
assets = "../../assets/"

[package.metadata.android.activity_attributes]
"android:exported" =  "true"
"android:screenOrientation" = "userPortrait"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rogalik = { workspace = true }

hike_data = { path = "../hike_data" }
hike_game = { path = "../hike_game" }
hike_graphics = { path = "../hike_graphics" }

